version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:2055@db:5432/MovieDB
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: movie_frontend
    ports:
      - "5173:5173"
    restart: always

  db:
    image: postgres:17
    container_name: movie_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2055
      POSTGRES_DB: MovieDB
    ports:
      - "5432:5432"  # Exposed for backend and optional laptop pgAdmin
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
